import Head from "next/head";
import Link from "next/link";
import clsx from "clsx";
import { Rubik } from "next/font/google";
import { useCallback, useEffect, useState } from "react";

const font = Rubik({
  subsets: ["latin-ext"],
});

export default function Home() {
  const [token, setToken] = useState<string | null>(null);
  const receiveMessage = useCallback((event: MessageEvent) => {
    if (
      event.origin !== "http://localhost:3000" &&
      event.origin !== "https://parent-localstorage.vercel.app"
    )
      return;
    localStorage.setItem("token", event.data as string);
    setToken(event.data as string);
  }, []);

  useEffect(() => {
    window.addEventListener("message", receiveMessage, false);
    return () => window.removeEventListener("message", receiveMessage);
  }, []);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={clsx("flex min-h-screen flex-col", font.className)}>
        <nav className="bg-green-100 px-20 py-2">
          <span className="text-xl font-semibold">Child App</span>
        </nav>
        <div className="px-20 py-4">
          {token ? (
            <span className="font-mono text-xl text-gray-700">{token}</span>
          ) : null}
        </div>
      </main>
    </>
  );
}
